name: Build Release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    env:
      VERSION: 1.0.${{github.run_number}}
    steps:
      - name: Checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Apple Xcode certificates
        uses: apple-actions/import-codesign-certs@8f3fb608891dd2244cdab3d69cd68c0d37a7fe93 # v2.0.0
        with:
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.APP_CERTIFICATES_P12_MAOS }}
          p12-password: ${{ secrets.APP_CERTIFICATES_P12_PASSWORD_MAOS }}
      - name: Install Apple Installer certificates
        uses: apple-actions/import-codesign-certs@8f3fb608891dd2244cdab3d69cd68c0d37a7fe93 # v2.0.0
        with:
          create-keychain: false # do not create a new keychain for this value
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.PKG_CERTIFICATES_P12_MAOS }}
          p12-password: ${{ secrets.PKG_CERTIFICATES_P12_PASSWORD_MAOS }}
      - name: Build package
        run: ./tools/build_pkg.zsh $VERSION ${{ secrets.NOTARY_APP_PASSWORD_MAOS }}
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@d552ecf3366cf9d6da9fd7dbe425325d3d095aa8 # v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          reverse: 'true'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          name: v$VERSION
          tag_name: v$VERSION
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # What's Changed
            ${{ steps.changelog.outputs.changelog }}
          files: output/*.pkg
